### ISSUE TITLE
bug : ./env.sh ./script/create_cita_config.py create --help

### ISSUE THREAD

**Issue by Wuyanz** [cryptape/cita#179]
./env.sh ./script/create_cita_config.py create --help
docker container cita_run_Users_macos_cita_cita_secp256k1_sha3 is already running
error: exec: "./script/create_cita_config.py": stat ./script/create_cita_config.py: no such file or directory

./env.sh ./scripts/create_cita_config.py create --help
docker container cita_run_Users_macos_cita_cita_secp256k1_sha3 is already running
usage: create_cita_config.py create [-h]

mac os high sierra 10.13
docker version 18.06.0-ce

**Comment by driftluo** [comment]
The first command, the directory you entered has a problem, this directory does not exist.

The second command, I don't know what the problem is. If you have a problem with the `./scripts/create_cita_config.py` file, just go to the corresponding version of the source code and overwrite the file with your problem with `scripts/create_cita_config.py`. 

> Note that this script does not exist in version 0.16.

I have checked that in the latest code, this file is correct.

**Comment by itlabers** [comment]
Thread main panicked at failed to open url amqp://guest:guest@localhost/test-chain/0 : Protocol("Connection reset by peer (os error 104)"), /opt/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/4f6bbf9/pubsub_rabbitmq/src/lib.rs:58

This is a bug. Please report it at:

    https://github.com/cryptape/cita/issues/new
