### ISSUE TITLE
start node 0  errror

### ISSUE THREAD

**Issue by itlabers** [cryptape/cita#180]
# Issue Template

## Description

[Description of the issue]

## Steps to Reproduce

Thread main panicked at failed to open url amqp://guest:guest@localhost/test-chain/0 : Protocol("Connection reset by peer (os error 104)"), /opt/.cargo/git/checkouts/cita-common-1aad419f3e80ba17/4f6bbf9/pubsub_rabbitmq/src/lib.rs:58

This is a bug. Please report it at:

    https://github.com/cryptape/cita/issues/new

**Comment by driftluo** [comment]
Because rabbitmq is not started, microservices cannot communicate with rabbitmq.

There are several possibilities here:
1. the existing existing RabbitMQ, the porter internally started RabbitMQ will have port conflicts
2. docker starts on mac, `- net = host` this parameter is invalid, and will cause problems with the entire docker startup, rabbitmq initialization will fail
3. did not execute `./env.sh bin / cita setup xxx` operation, this operation is used to initialize rabbitmq
